### ISSUE TITLE
Places API Key not found

### ISSUE THREAD

**Issue by rajaborntohack1** [vermayash8/TaskNearby#79]
C:\Users\rajab\AndroidStudioProjects\TaskNearby\app\build\intermediates\instant_run_merged_manifests\debug\processDebugManifest\instant-run\AndroidManifest.xml:145: AAPT: error: resource string/places_api_key (aka app.tasknearby.yashcreations.com.tasknearby.debug:string/places_api_key) not found.

**Comment by rryk** [comment]
+1, this makes it harder to contribute

**Comment by rryk** [comment]
Looks like this is the template for the API key file is here: https://github.com/vermayash8/TaskNearby/blob/master/app/src/main/res/values/keys_template.xml.

Given that one has to setup billing even for testing, I can now understand why the author of this project could not commit the original file. However, this is preventing users from even completing the Gradle sync. Have you considered adding keys.xml with bogus entry while keeping the file ignored via .gitignore? This way you will make sure that actual key is never marked for commit, while also keeping it easy to start contributing?

I will create a PR for the suggestion above.

**Comment by rryk** [comment]
Actually just un-commenting <string> entries in keys_template.xml is sufficient.

**Comment by rajaborntohack1** [comment]
thank u sir

**Comment by Shilpi75** [comment]
Thanks @rryk. 
@rajaborntohack1 :
https://github.com/vermayash8/TaskNearby/blob/master/app/src/main/res/values/keys_template.xml : This is the template for API keys. You can just uncomment it, enter your API key and start building. You can get the API key from [here](https://developers.google.com/places/web-service/get-api-key). 
We'll try to change the mechanism to make it more intuitive.

**Comment by rajaborntohack1** [comment]
thank u mam
