### ISSUE TITLE
Does not work on Android 10

### ISSUE THREAD

**Issue by rryk** [vermayash8/TaskNearby#87]
Reminders do not work despite allowing location access and disabling battery optimization.

**Comment by vermayash8** [comment]
Hey @rryk  - We've fixed this issue in release v4.1.0 (24). This has been released to our customers via Google Play.

The code changes are currently in develop branch and we're merging them to master.

**Comment by rryk** [comment]
Oh, that's good to hear. I've essentially abandoned using the app due to this bug. Will make sure to test again.

**Comment by rryk** [comment]
P.S. I am curious, on the technical side, what did you need to change to make it work? Is there a particular commit I can look at?

**Comment by vermayash8** [comment]
Please see PR #91 and #92 for the fix.
